import type { Metadata } from "next";
import {Inter as FontSans} from "next/font/google";
import { cn } from "@/lib/utils";

import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-gray-50 text-gray-800 font-sans antialiased transition-colors duration-200",
          fontSans.variable
        )}
      >
        <main className="container mx-auto pt-10 pb-10 px-4">
          <header className="mb-10 text-center">
            <h1 className="text-4xl font-bold text-gray-900">
              Terrific assessment
            </h1>
            <p className="mt-2 text-lg text-gray-600">
              A single app for your tasks!
            </p>
          </header>
          <div className="bg-white shadow-md rounded-lg p-6">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
